apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: shipping-on-the-air
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: order-service
        static_configs:
          - targets: ["order-service.shipping-on-the-air.svc.cluster.local:8001"]
        metrics_path: /metrics
      - job_name: shipment-orchestrator
        static_configs:
          - targets: ["shipment-orchestrator.shipping-on-the-air.svc.cluster.local:8002"]
        metrics_path: /metrics
      - job_name: drone-service
        static_configs:
          - targets: ["drone-service.shipping-on-the-air.svc.cluster.local:8003"]
        metrics_path: /metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: shipping-on-the-air
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.52.0
          args:
            - --config.file=/etc/prometheus/prometheus.yml
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: cfg
              mountPath: /etc/prometheus
      volumes:
        - name: cfg
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: shipping-on-the-air
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
